### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [ChristopherHaws/mc-expanded-enderchest#52]

**Comment by ChristopherHaws** [comment]
I haven't had a chance to check if it is working (been super busy with work) but there is a 1.20 build that you can download and try out here: https://github.com/ChristopherHaws/mc-expanded-enderchest/actions/runs/5124650229

**Comment by sternschnaube** [comment]
Hiho @ChristopherHaws, I was testing this build right now.
Everything works on 1.20.1 - thank you so much 😊

I let you close it, until it's released public.

**Comment by allanonmage** [comment]
If this works, can you publish it on Modrinth please?

**Comment by ChristopherHaws** [comment]
Updated versions have been published to curseforge and modrinth. Sorry for the wait, been super busy.
